title:              Hyun Seung's Blog
email:              hslrock@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             Hyun Seung Lee
baseurl:            ""
url:                "https://hslrock.github.io"

# Social Profiles
twitter_username:   
github_username:    hslrock
facebook_username:  """"
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-155741519-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
